name: Build & Push Node API

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ DockerHub login
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3️⃣ Build & Push Node Docker Image
      - name: Build & Push Docker Image
        run: |
          docker build -t nisha783876/node_api:latest .
          docker push nisha783876/node_api:latest

      # 4️⃣ Deploy to AWS / Server
      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker pull nisha783876/node_api:latest
            docker stop node_api || true
            docker rm node_api || true
            docker run -d \
              --name node_api \
              -p 8000:8000 \
              --env-file .env \
              nisha783876/node_api:latest

              